{% set version = "0.2" %}

package:
  name: otsvm
  version: {{ version }}

source:
  fn: otsvm-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otsvm/archive/v{{ version }}.tar.gz  # [not win]
  sha256: a00672da0ebcf14f7429fbf7296a11a21b3f1878053ab02746ae6dbe8eb332c0  # [not win]

  fn: otsvm-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otsvm-{{ version }}-py2.7-i686.exe  # [win32 and py27]
  sha256: c476c73668ff9f37260540838fa40982bd77244a34321f9734ed01795c01249d  # [win32 and py27]

  fn: otsvm-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build/releases/download/v1.8/otsvm-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: bfebff2aa95ca530d7b9f486a056cc0a2eb25dada0b1560d10c2f31cdcd8637b  # [win64 and py27]

  fn: otsvm-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otsvm-{{ version }}-py3.4-i686.exe  # [win32 and py34]
  sha256: 038ffcd9c46871ab59eb16a00122139858ee42001300b53612ceac35f86fdbb5  # [win32 and py34]

  fn: otsvm-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  url: https://github.com/openturns/build/releases/download/v1.8/otsvm-{{ version }}-py3.4-x86_64.exe  # [win64 and py34]
  sha256: 070e0f85841ebde47de937b189c065f2b15784d606d2d00ba238d9995ce8db78  # [win64 and py34]

  fn: otsvm-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otsvm-{{ version }}-py3.5-i686.exe  # [win32 and py35]
  sha256: 0581c8c27260924c7e16e8adc6c1ae5b681560803f16cefe753bd05499aab2e3  # [win32 and py35]

  fn: otsvm-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build/releases/download/v1.8/otsvm-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: fe4e38388721ec0ee0066c8f91b2211913d6c7591aebeb3e3fa978cf44f1a5b9  # [win64 and py35]

build:
  number: 2

requirements:
  build:
    - toolchain
    - python
    - cmake  # [not win]
    - swig  # [not win]
    - openturns  # [not win]

  run:
    - python
    - openturns

test:
  imports:
    - otsvm

about:
  home: http://openturns.org/
  license: LGPLv3
  license_file: COPYING.LESSER  # [not win]
  summary: SVM module

extra:
  recipe-maintainers:
    - jschueller
