travis:
  secure:
    BINSTAR_TOKEN: ItNz9FPjegx7XEPckkCuTJ7e0L+u73o5Pg18Ww+a93B2yLu2LEcP7qX5AW9GjzRXvNQn+k1wMUsbYis+xdc/Jmz9oKBNJOVEHSNcAgyYrb+emCGh4oWR3Dx1w0HLJBsiHfjZ18DzcSDfHrIXpc1WCI+clGz0qcAPFsrMrqDXVRhbEuv7KF2XBFD9M99f/RZyrx6YmJ0I0d7uKQJO0G4suJlS4NO5VsBNtceVAuya8dJ/B97MZaCMAAI8jZrmgCRwoT0cziQTxwU50Lhmd18yBBq2o3Clz+9OZgRqaMIu1bNowRksqyvIS8Pt9vJ2oZz6GdqB14I0xbpYnM1W6PSux47QI6lO7UaWEu/BZgEsx7KBmjTf/VSuhwE55PIx+nf0MS/t0+8Fy4Xf8y8TJpJJZR8r55CcbxdHytxMN0sS+U7Xht6MXyD2Bj+V6eXidqwNclzzMIJNPv60/GJC95LT1oA+sh5YJlQntRxm5RPYhJ2UyRGAIGGaB0oW6z7PQhPaUP6Uttwq0Ab58/OsANJ9ESl2kc2igD+kHLmtSkO0TUW3ro/YuZXBpeRFGGw3XyBlrGoGhKdrUDaEDUbCIhkncU11iCEOXhnvDPksRx2SR5BRCW0PfYtJ7CJnQBJFQsupXJYzVhPJyBv2K8MtkW/HbcgooUPWrF1V1KVwe0r8Hn4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
